
func test(x, y, z)
    for i=(1,5) do
        try do
            var x = 2;
        catch ObjectException do
            try do
                #Тут намеренная ошибка синтаксиса
                print "ObjectException 1", x
            catch SyntaxException do
                print "SyntaxException 2";
            end_try
        end_try
        print "Hello!", x, loop_i;

        print "x: ", func_x, "y: ", func_y, "z: ", func_z;
    end_loop

    print "END_LOOP";

    try do
        print loop_i;
    catch ObjectException do
        print "ObjectException 3";
    end_try

    print "END_TRY1";

    print "x: ", func_x, "y: ", func_y, "z: ", func_z, "END";
    print "END FUNC";
end_func

test(1, 2, 3);


try do
    print "test";

    # Ошибка, попытка переопределить переменной
    var x = 2;
catch ObjectException do
    try do
        print "ObjectException 4", x
    catch SyntaxException do
        print "SyntaxException 5";
    end_try
end_try


print "END_TRY2";

try do
    try do
        # Ошибка, обращение к неизвестной переменной
        print loop_i;
    catch ObjectException do
        print "ObjectException 6";
    end_try
catch ObjectExcepti2on do
    print "ObjectException 7";
end_try


print "test 2";

test(1, 2, 3);

for _=(1,20) do
    print "FINAL_FOR";
end_loop
