
func test()
    for i=(-1,20) do
        try do
            var x = 2;
        catch ObjectException do
            print "ObjectException 1", x;
        end_try
        print "Hello!", x;
    end_loop
end_func

test();
