var arr = {1,2,3,4};
         # 0 1 2 3
try do
    print arr[0];
    print arr[1];
    print arr[2];
    print arr[3];
    print arr[4];
catch IndexException do
    print "IndexException!!!";
end_try


func test(x, y, z)
    for i=(1,1) do
        try do
            var x = 2;
        catch ObjectException do
            try do
                #Тут намеренная ошибка синтаксиса
                print "ObjectException 1", x
            catch SyntaxException do
                print "SyntaxException 2";
            end_try
        end_try
        print "Hello!", x, loop_i;

        print "x: ", func_x, "y: ", func_y, "z: ", func_z;
    end_loop

    print "END_LOOP";

    try do
        print loop_i;
    catch ObjectException do
        print "ObjectException 3";
    end_try

    print "END_TRY1";

    print "x: ", func_x, "y: ", func_y, "z: ", func_z, "END";
    print "END FUNC";
end_func

test(1, 2, 3);


try do
    print "test";

    # Ошибка, попытка переопределить переменной
    var x = 2;
catch ObjectException do
    try do
        print "ObjectException 4", x
    catch SyntaxException do
        print "SyntaxException 5";
    end_try
end_try


print "END_TRY2";

try do
    try do
        # Ошибка, обращение к неизвестной переменной
        print loop_i;
    catch ObjectException do
        print "ObjectException 6";
    end_try
catch ObjectExcepti2on do
    print "ObjectException 7";
end_try

Add(1, 2);
OS_command("echo 123");
Len("aaaqweqe");
Print(1,2,3);

print "test 2";

test(1, 2, 3);


try do
    var x = 2
catch ObjectException do
    print "ObjectException 1";
catch SyntaxException do
    print "SyntaxException 2";
end_try

print x;

